version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'Development'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'localsql!'
      MYSQL_ROOT_PASSWORD: 'localsql!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: